- name: install rpms
  yum:
    name: "{{ packages }}"
    state: latest

- name: Gather service facts
  service_facts:
  register: services_state

- name: open ports on firewall
  firewalld:
    port: "{{ item[1] }}"
    state: enabled
    immediate: yes
    permanent: yes
    zone: "{{ item[0] }}"
  with_nested:
    - "{{ zones }}"
    - "{{ ports }}"
  when: ansible_facts.services['firewalld.service'] is defined and
        ansible_facts.services['firewalld.service'].state == 'running'
