- name: add internal dns records
  nsupdate:
    key_name: "{{ dns_key_name_internal }}"
    key_secret: "{{ dns_key_secret_internal }}"
    server: "{{ dns_private_ip }}"
    zone: "{{ item.zone }}"
    record: "{{ item.name }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
  with_items: "{{ records | b64decode }}"

- name: add external dns records
  nsupdate:
    key_name: "{{ dns_key_name_external }}"
    key_secret: "{{ dns_key_secret_external }}"
    server: "{{ dns_public_ip }}"
    zone: "{{ item.zone }}"
    record: "{{ item.name }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
  with_items: "{{ external_records | b64decode }}"